FROM amd64/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN apt-get update && apt-get install -y bash net-tools && apt-get clean

RUN useradd -ms /bin/bash procyon

RUN mkdir /etc/procyon

RUN mkdir /var/lib/procyon

RUN chown procyon:procyon /etc/procyon /var/lib/procyon

WORKDIR /home/procyon

COPY --chown=procyon:procyon linux64/* /home/procyon/

COPY --chown=procyon:procyon run.sh /home/procyon/

USER procyon

CMD ["/home/procyon/run.sh"]
